### PR TITLE
add docs comparing oc and kubectl

### PR DESCRIPTION
**Pull request by juanvallejo**
Draft of new docs comparing kubectl to oc.
Trello card: https://trello.com/c/BumbnGUY

Opening here first in order to gather sufficient feedback / vet any of the information in the docs.

cc @mfojtik @deads2k

### CODE REVIEW

**Comment by juanvallejo** [comment]
@mfojtik @deads2k friendly ping

cc @liggitt

**Comment by juanvallejo** [comment]
cc @derekwaynecarr

**Comment by mfojtik** [comment]
@juanvallejo can we also add notion that users can "convert" the "oc" binary to kubectl by copying/renaming it?

**Comment by liggitt** [comment]
> @juanvallejo can we also add notion that users can "convert" the "oc" binary to kubectl by copying/renaming it?

do we want people doing this?

**Comment by juanvallejo** [comment]
@mfojtik 
> > @juanvallejo can we also add notion that users can "convert" the "oc" binary to kubectl by 
> > copying/renaming it?

@liggitt 
> do we want people doing this?

I think if we do add this, we should stress that users will not have access to the features mentioned under `oc`.

**Comment by juanvallejo** [comment]
Closing, this has been opened against the openshift-docs repo.

**Pull request closed without merging**
